### ISSUE TITLE
Surprising unsat failure in compilation

### ISSUE THREAD

**Issue by mark-schultz** [PLSysSec/FaCT#60]
I have an issue where a rather basic program that uses uint16's compiles, while a corresponding version that uses uint32's doesn't (and gives an "unsat" error). I've attached the corresponding files, but can't seem to debug it.

[error.zip](https://github.com/PLSysSec/FaCT/files/3527839/error.zip)

**Comment by scauligi** [comment]
The problem is that LEN is 2 ** 32, which is not a valid number for a uint32, and will be truncated to 0.
This results in a(n unintended) vacuous loop, which the checker detects and errors out on.
Setting the constant to 4294967295 (2**32 - 1) allows compilation to proceed without error.
